sdhz151/android_vendor_cm

- build/core/maven_artifact_publish.mk
Change-Id: Ie0b81e46823e15b1cadfd1426f6d6cbb6daf4e10
TICKET: CYNGNOS-2305
> cm: Support maven artifact as aar for publish.

- prebuilt/common/etc/apns-conf.xml
Change-Id: I4157f810f7b0663b353aa664eb3f765fef9158ec
> SMART [PH] APN updates

- config/cmsdk_common.mk
- config/permissions/org.cyanogenmod.livedisplay.xml
- sepolicy/service.te
- sepolicy/service_contexts
* Also alphabetized the list of feature xmls, you filthy pigs.
Change-Id: I094a46c313be4531c6dd1af1e007a26b2476d60e
> cm: Moving LiveDisplay to CMSDK

- prebuilt/common/etc/apns-conf.xml
mnc="1" != mnc="01"
Change-Id: I1eb77fa365d0d06b9a11671be576a6c9b7bd28f9
> APN: fixup single-digit mnc APNs

- prebuilt/common/etc/apns-conf.xml
Issue-id:FEIJ-44
Change-Id: Ie1e52575f61764e5811d71da8930a88b139deb78
> Update APN name for Movistar INTERNET

- build/core/apicheck_msg_current.txt
Change-Id: Idfa73b8ec3f9375766e01d8fb7b69079d776b751
> cm: Amend api text message.

- prebuilt/common/etc/apns-conf.xml
Change-Id: Ie0a929fc4bc9659163b08beb1246ba0196c8d14b
> Irancell & MTS APN updates

- overlay/common/packages/services/Telecomm/res/values/cm_config.xml
- overlay/common/packages/services/Telephony/res/values/cm_config.xml
Ticket CD-544
Change-Id: I4c14bb05959f5db264bb61c65cc9031e7836b972
> Remove cyngn dialer

- sepolicy/qcom/dumpstate.te
Change-Id: I14338a03c469cd71a6d5c7fecc71eb2290b2e6c4
> cm: Add SE policy for iop service

- overlay/common/frameworks/base/core/res/res/values/cm_arrays.xml
Without this patch, you will enter permission rejection hell.
RM-232
Change-Id: Ifa3fd57b97dee280083035f1086e988ac649eaef
> Prep for C-Apps support

- config/common.mk
Change-Id: I89124cd684f40b48099ce32be3e20111c044c8a0
> cm: Build DataUsageProvider

- prebuilt/common/etc/apns-conf.xml
Change-Id: I5ba539d6d909c108192ffce5ec18c2b0b17c1d12
> APN: Add Straight Talk Verizon APN

- prebuilt/common/etc/apns-conf.xml
Change-Id: I8ea1c5cb60e13406fb11585c19653f673a0f0793
> update COOPVOCE apn

- overlay/common/frameworks/base/core/res/res/values/config.xml
Change-Id: If779cf1de45cfc4eafeec80361490b003559ef14
> cm: enable lockscreen rotation option

- sepolicy/qcom/property_contexts
Issue-id:FEIJ-679
Change-Id: Iafe0405fd4a83c8f22e1af7152c1c3a009cd2e71
> persist.dbg/data for radio to control QC prop's

- gello/Android.mk
Change-Id: Ie15fad792d0d8840bccdb9579bd1d2aae9ae27d9
> Gello: Update to v20 artifact

- build/tasks/generate_cmsdk_coverage.mk
Change-Id: I8610f402d7c9a55213a520f317d7c94074c96df9
> cm: Use cmsdk-api-coverage executable for coverage.

- CONTRIBUTORS.mkdn
Change-Id: Ia19c90f655bc504006b7bf3457791962ba6b0c09
> Add SM-T810 and SM-T815

- CONTRIBUTORS.mkdn
Change-Id: Ic2c7693ef173b0d63890567ee48738c04b8967ce
> T810: Build by T_I, based on T815 build of RaymanFX, added product name

- overlay/common/frameworks/base/core/res/res/values/config.xml
Change-Id: I57f50a92a38fd8f4887b341914dc8687b8616fb4
Signed-off-by: Joey Rizzoli <joey@cyanogenmoditalia.it>
> cm: overlay: enable otg notification

- prebuilt/common/etc/apns-conf.xml
* Add IMS APN for AT&T
* Add magical? parameter for TMO
Change-Id: Idd4d74cf04894467ce51a97d73abb74aba0e1021
> cm: minor IMS APN update

- build/tools/extract_utils.sh
Change-Id: I2d893a3f8472a86835feef24540e82c47b69fd67
> cm: Remove stray echo from extract_utils

- gello/Android.mk
Change-Id: Icd15825eff33a3f5d14108186a111a77cd9f2770
> Gello artifact v26

- sepolicy/kernel.te
* Do not carry forward into N release.
Change-Id: I1f90695c48ac5a19848efafb146eabdff1ca4b6a
> sepolicy: Add rule to allow sdcardfs to read package list

- prebuilt/common/etc/apns-conf.xml
Issue: CMM-42
Change-Id: I31a1f2774b9de8278ec67810ca55503800cc8a06
> Add missing truphone APNs

- sepolicy/mediaserver.te
Change-Id: Icc892d8b2c34950431564738b66d8e8baefc62be
> sepolicy: Allow media_rw write to fix camcorder denials

- sepolicy/system_server.te
Change-Id: Ia6fc26781c1cb576c2feee3e941d7206e7878bb5
> cm: sepolicy: Allow system_server dir read access

- sepolicy/kernel.te
Change-Id: I8fe011140798925ee5b5926355868febd595a788
> sepolicy: Fix MTP for sdcardfs

- sepolicy/livedisplay.te
- sepolicy/qcom/livedisplay.te
* Don't wanna break the build for anyone again :(  The
native stuff is very QCOM specific and won't work elsewhere.
Change-Id: Id5dbba1a46dc12cbd5914cf3072ed92a72039b31
> sepolicy: Move new QCOM-specific policy to the right place

- CONTRIBUTORS.mkdn
Change-Id: Ia7d140ea3810df186c9dd38905361a8cf278e312
> Added contributors for vegetalte

- CONTRIBUTORS.mkdn
Change-Id: I47432d8f9e99a8d743c5629ae7fe718c1a4067d3
> Contributors: Add maintainer for Alcatel Idol 3

- build/tools/repopick.py
Change-Id: I0673779363b1963219a2765399f2e20c9cdd78a8
> repopick: fix indentation derp

- sepolicy/system_app.te
- sepolicy/system_server.te
Change-Id: I78a5570f330e703b7f7ac2b34370a83bbb2a0d87
> sepolicy: Fix adbsecure_prop denials

- gello/Android.mk
Change-Id: Iac70d70296244863ae766facc1a926745fe48e63
> Gello artifact v40

- build/envsetup.sh
Change-Id: Iec38c313c9eb88a74c7bf7a5cf424131b568ac0a
> cm: mka nicer

- overlay/common/frameworks/base/core/res/res/values/config.xml
* Google has added its own implementation in 7.1
Change-Id: I0a4890adcfeaa4a7b6463754c6b4d73b73e5f12e
> cm: overlay: Use restart action

- prebuilt/common/etc/apns-conf.xml
Change-Id: I4b44ce88abaf794f47683d13ed3b91172dea03ef
Signed-off-by: Hriday Sharma <hridaysharma42@gmail.com>
> apns: Add Reliance Jio apn's

- config/common.mk
Change-Id: I18ac1f27d73837e08d25f441543faf30cc58f8ee
Signed-off-by: Joey Rizzoli <joey@cyanogenmoditalia.it>
> cm: enable hidden storage manager

- bootanimation/generate-bootanimation.sh
Change-Id: Iec90f3521e589de4e8352c0349e1a0751d65d989
> bootanim: Use a for loop to make part# folders

- CONTRIBUTORS.mkdn
Change-Id: I90e0e90185aaee735c18ccde8e812ffe84a14bb6
> Contributors: Add maintainer for Xiaomi Redmi 3/Prime (ido)

- CONTRIBUTORS.mkdn
Change-Id: I3ca16eeec0fd30150f2ca7277151135e42ec291a
> Contributors: Add maintainer for ARK Benefit A3(peach)
